# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc84143961656852d90cd358fe4abe08284867491eccd992cd39af18a3327b737c34689b667f28584baf0f5ef194f5a2b29640051f94bdade24f1210e334f69

test:
  secret_key_base: c41d10e272edd8bb31950996313c2557bed8c7fda39d1a03183056f8882170a50440869cc83e957bbddd1734c2c95b25a7469761aad63d0b3e5edf4c2d3014a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
